### ISSUE TITLE
Method order questions

### ISSUE THREAD

**Issue by izanf** [ebceu4/waves-transactions#20]
Is it no longer possible to create a purchase order specifying the currency I want to buy and the currency I want to pay?

What would be the seed parameter that is needed in the method?

**Comment by izanf** [comment]
In the createOrder method I would pass the following object as a parameter:
` {
      matcherPublicKey: MATCHER_PUBLIC_KEY,
      publicKey: data.keyPair.publicKey,
      amountAsset: CURRENCY_TO_BUY,
      priceAsset: data.currencyToPay,
      orderType: 'buy',
      amount: 2000000000,
      price: 100000,
      timestamp: Date.now(),
      expiration: expirationDate(),
      matcherFee: 300000
    }`


With this I could specify the currency I wanted to buy and the currency I wanted to pay, but I did not understand how this works in this new lib.

**Comment by izanf** [comment]
Do you believe that waves-transactions are stable for use in a production app?

**Comment by siemarell** [comment]
Copy pasted from docs and added amountAsset as example.
```javascript
const { order } = require('waves-transactions')

const seed = 'seed phrase to sign order'

const params = {
  amount: 100000000, //1 waves
  price: 10, //for 0.00000010 BTC
  priceAsset: '8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS',
  amountAsset: 'someAsset',
  matcherPublicKey: '7kPFrHDiGw1rCm7LPszuECwWYL3dMf6iMifLRDJQZMzy',
  orderType: 'buy'
}


const signedOrder = order(params, seed)
```

We use waves-transaction in [web ide](https://testnet.ide.wavesplatform.com/). But we dont use orders there. Keep in mind that for now, you cannot publish order via this library. You can only create it.

**Comment by izanf** [comment]
On https://ebceu4.github.io/waves-transactions/globals.html#order show this data structure: 
`const { order } = require('waves-transactions')

const seed = 'b716885e9ba64442b4f1263c8e2d8671e98b800c60ec4dc2a27c83e5f9002b18'

const params = {
  amount: 100000000, //1 waves
  price: 10, //for 0.00000010 BTC
  priceAsset: '8LQW8f7P5d5PZM7GtZEBgaqRPGSzS3DfPuiXrURJ4AJS',
  matcherPublicKey: '7kPFrHDiGw1rCm7LPszuECwWYL3dMf6iMifLRDJQZMzy',
  orderType: 'buy'
}


const signedOrder = order(params, seed)`

**Comment by siemarell** [comment]
Yes. I have added amountAsset as an example. Do you mean that you got confused because there were no amountAsset in the docs?

**Comment by siemarell** [comment]
Ty for information. Params can be found here: https://ebceu4.github.io/waves-transactions/interfaces/orderparams.html. We will fix examples not to confuse people

**Comment by izanf** [comment]
Another question, how can I generate the seed?

**Comment by izanf** [comment]
You mentioned above that I can not publish the order with this method, what would be the method to publish the order?

**Comment by siemarell** [comment]
You can use native 'fetch' or any http library to send order as json to via POST to https//nodes.wavesplatform.com/transactions/broadcast

**Comment by siemarell** [comment]
There is no such functionality as seed generation. At least for now. You can try [this](https://www.npmjs.com/package/bip39) package. I use it to generate seeds in IDE

**Comment by izanf** [comment]
Dude, thanks for the help. You were the first to help me enough in months. I work as a developer on a Brazilian fintech and we are developing our solution on the blockchain of waves.

**Comment by siemarell** [comment]
You are welcome. Just for you yo know: 1 this repository is moving to wavesplatform. So npm package is @waves/waves-transaction. 2 you can ask questions in waves discord channel
