### ISSUE TITLE
Бинарные значения в Data Transaction

### ISSUE THREAD

**Issue by bodrych** [ebceu4/waves-transactions#3]
Было бы здорово, если бы можно было указывать значение бинарного поля в base64 формате
```
{
  "version" : 1,
  "sender": "3FjTpAg1VbmxSH39YWnfFukAUhxMqmKqTEZ",
  "data": [
    {"key": "blob", "type": "binary", "value": "base64:BzWHaQU"}
  ],
  "fee": 100000
}
```
(код из [документации](https://docs.wavesplatform.com/en/technical-details/data-transaction.html))

**Comment by siemarell** [comment]
For now this library automatically derives types. E.x. 
```javascript 
{key:"blob", "value": "base64:BzWHaQU"}
```
Derived type would be "string". You can convert your base64 string to array before using library "data" function

**Comment by ebceu4** [comment]
Можно указывать в бинарном просто value должно быть Uint8Array.from([1,2,3])

**Comment by siemarell** [comment]
Начиная с версии 2.0 можно указывать:
```javascript
{"key": "blob", "type": "binary", "value": "base64:BzWHaQU"}
```
тип не будет автоматически выводиться в таком случае
