### ISSUE TITLE
Problem in broadcasting the transaction

### ISSUE THREAD

**Issue by srishti-khandelwal** [ebceu4/waves-transactions#7]
Hello Team,

I followed the code snippet to create a signed transaction with this as reponse: 
```
{ type: 4,
  version: 2,
  recipient: '3NCSW8KrUhQ4g711zJBuzdUmhop4NWV6yQf',
  attachment: undefined,
  feeAssetId: undefined,
  assetId: undefined,
  amount: 1,
  fee: 100000,
  senderPublicKey: '9GnFW2EYMryQLKCovwLCvE8KSniBMTqFuDCGZrRcCdbs',
  timestamp: 1540300429311,
  proofs:
   [ '3Q7pBFcgykoMRgqmbR2MKKWbo27SiFP3JsP6Gg5bdDhL3jyiKSGpWMGD1SMoKwPDChzt7a9AXDeL19Ebiin6Fgau' ],
  id: 'FBnNWPsFyPSAAHPZDXR2egyrsfEZurHNqaVLxxNjwLo6' }
```

now I am trying to broadcast it using this command: 
```      "type": 4, \ 
     "fee": 100000, \ 
     "senderPublicKey": "9GnFW2EYMryQLKCovwLCvE8KSniBMTqFuDCGZrRcCdbs", \ 
     "timestamp": 1540300429311, \ 
     "proofs": ["3Q7pBFcgykoMRgqmbR2MKKWbo27SiFP3JsP6Gg5bdDhL3jyiKSGpWMGD1SMoKwPDChzt7a9AXDeL19Ebiin6Fgau"], \ 
     "id": "FBnNWPsFyPSAAHPZDXR2egyrsfEZurHNqaVLxxNjwLo6" \ 
 }' 'http://localhost:6869/transactions/broadcast'  
```

But it is giving this response: 
`
{
  "error": 1,
  "message": "failed to parse json message",
  "cause": null,
  "validationErrors": {
    "obj.signature": [
      {
        "msg": [
          "error.path.missing"
        ],
        "args": []
      }
    ],
    "obj.recipient": [
      {
        "msg": [
          "error.path.missing"
        ],
        "args": []
      }
    ],
    "obj.amount": [
      {
        "msg": [
          "error.path.missing"
        ],
        "args": []
      }
    ]
  }
}
`

What am I doing wrong :(

Thanks for any Help :)

**Comment by siemarell** [comment]
Hello! Could you please explain how exactly do you broadcast the transaction? This library doesn't contain any transport methods and is used only to create and sign tx.

**Comment by srishti-khandelwal** [comment]
> Hello! Could you please explain how exactly do you broadcast the transaction? This library doesn't contain any transport methods and is used only to create and sign tx.
Thank you for your response. 

Yes, sure.
Actually i am having trouble in providing the seed as well, what seed are we suppose to provide exactly? 
I found seed at places: 
1) At the time when we setup the node, a **seed** is given in waves/configs/local.conf (node setup using docker path)
2) by hitting the end point `/addresses/seed/{address}` we get a **seed** in response.
which among the two are we suppose to use. Also there is no option to pick a sender from among the various addresses created from the node setup seed.

Beacause I can notice that the sender in response of transfer(), does not belong to any of my addresses.

**Comment by siemarell** [comment]
Seed is a string that uniquely identifies your account. Keypair is derived from it.
Please create a thread on https://forum.wavesplatform.com or use wavesplatform discord https://discord.gg/cnFmDyA and ask your question there. This project is a javascript library for creating transactions

**Comment by srishti-khandelwal** [comment]
Oh, Thank you for your response. I'll switch to that platform :)
